### ISSUE TITLE
pub global run rpi_serial:build_lib

### ISSUE THREAD

**Issue by teceP** [vinicentus/rpi_serial#1]
Hi, 

Iam getting an error when I want to execute `pub global run rpi_serial:build_lib`:

```
pi@raspi10:~/loraDart/LoRaDart $ pub global run rpi_serial:build_lib
Dart VM... /home/pi/dart-sdk/bin/dart
Dart SDK... /home/pi/dart-sdk
Building library in /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/lib
rpi_serial version 0.1.0
Unhandled exception:
ProcessException: No such file or directory
  Command: /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/lib/src/native/build_lib 2 /home/pi/dart-sdk
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:616:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      main (file:///home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/bin/build_lib.dart:47:31)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I did all steps from the setup section from here: https://pub.dev/packages/rpi_serial

rpi_serial should be active:

```
pi@raspi10:~/loraDart/LoRaDart $ pub global activate rpi_serial

Package rpi_serial is currently active at version 0.1.0.
Resolving dependencies... (1.5s)
+ path 1.7.0
+ rpi_serial 0.1.0
Precompiling executables... (10.5s)
Precompiled rpi_serial:build_lib.
Activated rpi_serial 0.1.0.
```

Would be happy if you could help me out :)

**Comment by samkhan2050** [comment]
Hi, i am facing the same problem. Did you manage to sort this out?

**Comment by samkhan2050** [comment]
> Hi,
> 
> Iam getting an error when I want to execute `pub global run rpi_serial:build_lib`:
> 
> ```
> pi@raspi10:~/loraDart/LoRaDart $ pub global run rpi_serial:build_lib
> Dart VM... /home/pi/dart-sdk/bin/dart
> Dart SDK... /home/pi/dart-sdk
> Building library in /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/lib
> rpi_serial version 0.1.0
> Unhandled exception:
> ProcessException: No such file or directory
>   Command: /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/lib/src/native/build_lib 2 /home/pi/dart-sdk
> #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473:7)
> #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:616:18)
> #2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
> #3      main (file:///home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_serial-0.1.0/bin/build_lib.dart:47:31)
> #4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
> #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
> ```
> 
> I did all steps from the setup section from here: https://pub.dev/packages/rpi_serial
> 
> rpi_serial should be active:
> 
> ```
> pi@raspi10:~/loraDart/LoRaDart $ pub global activate rpi_serial
> 
> Package rpi_serial is currently active at version 0.1.0.
> Resolving dependencies... (1.5s)
> + path 1.7.0
> + rpi_serial 0.1.0
> Precompiling executables... (10.5s)
> Precompiled rpi_serial:build_lib.
> Activated rpi_serial 0.1.0.
> ```
> 
> Would be happy if you could help me out :)

Hi @teceP , i am facing the same problem. Did you manage to sort this out?

**Comment by vinicentus** [comment]
Hi!

It's probably best to just migrate to [dart_serial_port](https://pub.dev/packages/dart_serial_port) instead. It should work on any Raspberry Pi platform.

I currently don't have the time to continue supporting this project, especially since there seem to be general and actively maintained libraries out there.
